# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4fcecd600eb33baab83b0d4da4d905ef57375436939a18d53abc75bce8ae8bd88c77b1c0ce52b34e4682916848a9a7af0d996139344fc581f9c249304b87b36

test:
  secret_key_base: 5433219bbe074af6f458645c88a517caa578a095ff84b79479b13275f265827a9923b8a5219d63646bb698e0b8963e5e038b313775c6737ca8cbc3d1a69c23ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
